create table if not exists public.society_service_complaints (
  id bigint generated by default as identity primary key,
  complaint_date date not null,
  service_type text not null,
  agency_id bigint references public.society_service_agencies(id) on delete set null,
  issue_count integer not null default 0 check (issue_count >= 0),
  issue_summary text,
  channel text not null default 'WHATSAPP' check (channel in ('WHATSAPP')),
  status text not null default 'PENDING'
    check (status in ('PENDING','WHATSAPP_OPENED','SENT','NOT_REQUIRED')),
  recipient_name text,
  recipient_mobile text,
  opened_at timestamptz,
  sent_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (complaint_date, service_type)
);

alter table public.society_service_complaints enable row level security;

grant select, insert, update on table public.society_service_complaints to authenticated;
grant usage, select on sequence public.society_service_complaints_id_seq to authenticated;

drop policy if exists "Authenticated users can read society service complaints"
  on public.society_service_complaints;

create policy "Authenticated users can read society service complaints"
  on public.society_service_complaints
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can insert society service complaints"
  on public.society_service_complaints;

create policy "Authenticated users can insert society service complaints"
  on public.society_service_complaints
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update society service complaints"
  on public.society_service_complaints;

create policy "Authenticated users can update society service complaints"
  on public.society_service_complaints
  for update
  to authenticated
  using (true)
  with check (true);
