alter table public.street_light_agencies
  add column if not exists contact_name text,
  add column if not exists mobile_no text;

update public.street_light_agencies
set mobile_no = coalesce(
  nullif(btrim(mobile_no), ''),
  nullif(btrim(whatsapp_no), ''),
  nullif(btrim(sms_no), '')
)
where mobile_no is null or btrim(mobile_no) = '';

create table if not exists public.street_light_notifications (
  id bigint generated by default as identity primary key,
  inspection_id bigint not null
    references public.street_light_agency_daily_inspections(id) on delete cascade,
  agency_id bigint not null
    references public.street_light_agencies(id),
  channel text not null check (channel in ('WHATSAPP','SMS')),
  recipient_name text,
  recipient_mobile text not null,
  message_text text not null,
  delivery_status text not null default 'PENDING'
    check (delivery_status in ('PENDING','SENT','FAILED','COMPOSER_OPENED')),
  provider_reference text,
  provider_response text,
  sent_by uuid references auth.users(id) on delete set null default auth.uid(),
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.street_light_notifications enable row level security;
grant select, insert, update on public.street_light_notifications to authenticated;

create policy "Authenticated users can read street light notifications"
  on public.street_light_notifications
  for select to authenticated
  using (true);

create policy "Authenticated users can insert street light notifications"
  on public.street_light_notifications
  for insert to authenticated
  with check (true);

create policy "Authenticated users can update street light notifications"
  on public.street_light_notifications
  for update to authenticated
  using (true)
  with check (true);

create index if not exists idx_street_light_notifications_inspection
  on public.street_light_notifications (inspection_id, created_at desc);
