-- Society inspection configuration + agency-based street-light inspection
create table if not exists public.society_inspection_settings (
  id smallint primary key default 1 check (id = 1),
  module_name text not null default 'Society Pulse'
    check (char_length(btrim(module_name)) between 2 and 60),
  theme_key text not null default 'blue'
    check (theme_key in ('blue','green','teal','orange','purple')),
  report_title text not null default 'DAILY SOCIETY INSPECTION SUMMARY'
    check (char_length(btrim(report_title)) between 2 and 100),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.society_inspection_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.society_inspection_settings enable row level security;
grant select, insert, update on public.society_inspection_settings to authenticated;

create policy "Authenticated users can read society inspection settings"
  on public.society_inspection_settings for select to authenticated using (true);
create policy "Authenticated users can insert society inspection settings"
  on public.society_inspection_settings for insert to authenticated with check (id = 1);
create policy "Authenticated users can update society inspection settings"
  on public.society_inspection_settings for update to authenticated
  using (id = 1) with check (id = 1);

create table if not exists public.street_light_agencies (
  id bigint generated by default as identity primary key,
  agency_code text not null unique,
  agency_name text not null,
  display_order integer not null default 0,
  active boolean not null default true,
  whatsapp_no text,
  sms_no text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.street_light_agencies
  (agency_code, agency_name, display_order)
values
  ('UPPCL', 'UPPCL', 1),
  ('TATA', 'TATA', 2)
on conflict (agency_code) do update
set agency_name = excluded.agency_name,
    display_order = excluded.display_order,
    active = true,
    updated_at = now();

alter table public.street_light_agencies enable row level security;
grant select, insert, update on public.street_light_agencies to authenticated;
create policy "Authenticated users can read street light agencies"
  on public.street_light_agencies for select to authenticated using (true);
create policy "Authenticated users can manage street light agencies"
  on public.street_light_agencies for all to authenticated using (true) with check (true);

create table if not exists public.street_light_agency_daily_inspections (
  id bigint generated by default as identity primary key,
  inspection_date date not null,
  agency_id bigint not null references public.street_light_agencies(id),
  faulty_count integer not null default 0 check (faulty_count between 0 and 200),
  remarks text,
  inspected_by uuid references auth.users(id) on delete set null default auth.uid(),
  saved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (inspection_date, agency_id)
);

alter table public.street_light_agency_daily_inspections enable row level security;
grant select, insert, update on public.street_light_agency_daily_inspections to authenticated;
create policy "Authenticated users can read agency street light inspections"
  on public.street_light_agency_daily_inspections for select to authenticated using (true);
create policy "Authenticated users can insert agency street light inspections"
  on public.street_light_agency_daily_inspections for insert to authenticated with check (true);
create policy "Authenticated users can update agency street light inspections"
  on public.street_light_agency_daily_inspections for update to authenticated using (true) with check (true);

create table if not exists public.street_light_fault_locations (
  id bigint generated by default as identity primary key,
  inspection_id bigint not null
    references public.street_light_agency_daily_inspections(id) on delete cascade,
  sequence_no integer not null check (sequence_no > 0),
  location_text text not null check (char_length(btrim(location_text)) > 0),
  status text not null default 'OPEN'
    check (status in ('OPEN','REPORTED','RESOLVED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (inspection_id, sequence_no)
);

alter table public.street_light_fault_locations enable row level security;
grant select, insert, update, delete on public.street_light_fault_locations to authenticated;
create policy "Authenticated users can read street light fault locations"
  on public.street_light_fault_locations for select to authenticated using (true);
create policy "Authenticated users can insert street light fault locations"
  on public.street_light_fault_locations for insert to authenticated with check (true);
create policy "Authenticated users can update street light fault locations"
  on public.street_light_fault_locations for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete street light fault locations"
  on public.street_light_fault_locations for delete to authenticated using (true);

create index if not exists idx_street_light_agency_daily_date
  on public.street_light_agency_daily_inspections (inspection_date);
create index if not exists idx_street_light_fault_locations_inspection
  on public.street_light_fault_locations (inspection_id);
