alter table public.society_inspection_settings
  add column if not exists supervisor_contact_name text,
  add column if not exists supervisor_contact_mobile text,
  add column if not exists rwa_contact_name text,
  add column if not exists rwa_contact_mobile text;

create table if not exists public.street_light_issues (
  id bigint generated by default as identity primary key,
  agency_id bigint not null
    references public.society_service_agencies(id),
  location_key text not null,
  location_text text not null,
  first_reported_date date not null,
  last_seen_date date not null,
  status text not null default 'OPEN'
    check (status in ('OPEN','RESOLVED')),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_street_light_open_issue
  on public.street_light_issues (agency_id, location_key)
  where status = 'OPEN';

create index if not exists idx_street_light_issues_status
  on public.street_light_issues (agency_id, status, first_reported_date);

alter table public.street_light_issues enable row level security;
grant select, insert, update on public.street_light_issues to authenticated;

create policy "Authenticated users can read street light issues"
  on public.street_light_issues for select to authenticated using (true);

create policy "Authenticated users can insert street light issues"
  on public.street_light_issues for insert to authenticated with check (true);

create policy "Authenticated users can update street light issues"
  on public.street_light_issues for update to authenticated
  using (true) with check (true);

alter table public.street_light_fault_locations
  add column if not exists issue_id bigint
    references public.street_light_issues(id) on delete set null;

insert into public.street_light_issues (
  agency_id,
  location_key,
  location_text,
  first_reported_date,
  last_seen_date,
  status
)
select
  i.agency_id,
  lower(regexp_replace(trim(f.location_text), '\s+', ' ', 'g')),
  trim(f.location_text),
  min(i.inspection_date),
  max(i.inspection_date),
  'OPEN'
from public.street_light_fault_locations f
join public.street_light_agency_daily_inspections i
  on i.id = f.inspection_id
where f.status in ('OPEN','REPORTED')
group by
  i.agency_id,
  lower(regexp_replace(trim(f.location_text), '\s+', ' ', 'g')),
  trim(f.location_text)
on conflict do nothing;

update public.street_light_fault_locations f
set issue_id = x.issue_id
from (
  select
    f2.id as fault_id,
    s.id as issue_id
  from public.street_light_fault_locations f2
  join public.street_light_agency_daily_inspections i
    on i.id = f2.inspection_id
  join public.street_light_issues s
    on s.agency_id = i.agency_id
   and s.location_key = lower(regexp_replace(trim(f2.location_text), '\s+', ' ', 'g'))
   and s.status = 'OPEN'
) x
where f.id = x.fault_id;
